export const STORE_USER_DATA = "STORE_USER_DATA";
export const STORE_TRIP_DATA = "STORE_TRIP_DATA";
export const GET_DRIVER_PROFILE = "GET_DRIVER_PROFILE";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_DRIVER_PROFILE = "SET_DRIVER_PROFILE";
export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";
